### ISSUE TITLE
True Client/Server Connectivity

### ISSUE THREAD

**Issue by ZetaTauEpsilon** [servusDei2018/TankistOnline#9]
When running Tankist in a true client/server configuration, the app becomes stuck infinitely loading.

Two issues must be rectified:

1) The server configuration must be edited to make use of address '0.0.0.0' rather than '127.0.0.1', owing to the fact that 127 is the loopback address.

2) The client listener must be able to find the server at this network address. No fix has been identified thus far.

**Comment by servusdei2018** [comment]
> The client listener must be able to find the server at this network address. No fix has been identified thus far.

I plan to make it so that clients have to specify the IP address of the server (via a future connection menu) from a list of public servers, and they'll have the option to enter a manual IP too. This'll probably be done next Spring; next release (a minor one that'll be out by mid-December) I'll work on adding a scrolling background so that it's easier to see your tank moving.
